/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MujerReNaceRouteImport } from './routes/mujer-re-nace'
import { Route as MentoriaMaestrasRouteImport } from './routes/mentoria-maestras'
import { Route as EntrevistaPreviaRouteImport } from './routes/entrevista-previa'
import { Route as DesdeLaRaizRouteImport } from './routes/desde-la-raiz'
import { Route as DarYRecibirRouteImport } from './routes/dar-y-recibir'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProtectedRouteImport } from './routes/admin/_protected'
import { Route as AdminProtectedIndexRouteImport } from './routes/admin/_protected/index'
import { Route as AdminProtectedSesionesRouteImport } from './routes/admin/_protected/sesiones'
import { Route as AdminProtectedProgramasRouteImport } from './routes/admin/_protected/programas'
import { Route as AdminProtectedMetodologiaRouteImport } from './routes/admin/_protected/metodologia'
import { Route as AdminProtectedEntrevistasRouteImport } from './routes/admin/_protected/entrevistas'

const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MujerReNaceRoute = MujerReNaceRouteImport.update({
  id: '/mujer-re-nace',
  path: '/mujer-re-nace',
  getParentRoute: () => rootRouteImport,
} as any)
const MentoriaMaestrasRoute = MentoriaMaestrasRouteImport.update({
  id: '/mentoria-maestras',
  path: '/mentoria-maestras',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistaPreviaRoute = EntrevistaPreviaRouteImport.update({
  id: '/entrevista-previa',
  path: '/entrevista-previa',
  getParentRoute: () => rootRouteImport,
} as any)
const DesdeLaRaizRoute = DesdeLaRaizRouteImport.update({
  id: '/desde-la-raiz',
  path: '/desde-la-raiz',
  getParentRoute: () => rootRouteImport,
} as any)
const DarYRecibirRoute = DarYRecibirRouteImport.update({
  id: '/dar-y-recibir',
  path: '/dar-y-recibir',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedRoute = AdminProtectedRouteImport.update({
  id: '/admin/_protected',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedIndexRoute = AdminProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedSesionesRoute = AdminProtectedSesionesRouteImport.update({
  id: '/sesiones',
  path: '/sesiones',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedProgramasRoute = AdminProtectedProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => AdminProtectedRoute,
} as any)
const AdminProtectedMetodologiaRoute =
  AdminProtectedMetodologiaRouteImport.update({
    id: '/metodologia',
    path: '/metodologia',
    getParentRoute: () => AdminProtectedRoute,
  } as any)
const AdminProtectedEntrevistasRoute =
  AdminProtectedEntrevistasRouteImport.update({
    id: '/entrevistas',
    path: '/entrevistas',
    getParentRoute: () => AdminProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/dar-y-recibir': typeof DarYRecibirRoute
  '/desde-la-raiz': typeof DesdeLaRaizRoute
  '/entrevista-previa': typeof EntrevistaPreviaRoute
  '/mentoria-maestras': typeof MentoriaMaestrasRoute
  '/mujer-re-nace': typeof MujerReNaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/admin': typeof AdminProtectedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/entrevistas': typeof AdminProtectedEntrevistasRoute
  '/admin/metodologia': typeof AdminProtectedMetodologiaRoute
  '/admin/programas': typeof AdminProtectedProgramasRoute
  '/admin/sesiones': typeof AdminProtectedSesionesRoute
  '/admin/': typeof AdminProtectedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/dar-y-recibir': typeof DarYRecibirRoute
  '/desde-la-raiz': typeof DesdeLaRaizRoute
  '/entrevista-previa': typeof EntrevistaPreviaRoute
  '/mentoria-maestras': typeof MentoriaMaestrasRoute
  '/mujer-re-nace': typeof MujerReNaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/entrevistas': typeof AdminProtectedEntrevistasRoute
  '/admin/metodologia': typeof AdminProtectedMetodologiaRoute
  '/admin/programas': typeof AdminProtectedProgramasRoute
  '/admin/sesiones': typeof AdminProtectedSesionesRoute
  '/admin': typeof AdminProtectedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/dar-y-recibir': typeof DarYRecibirRoute
  '/desde-la-raiz': typeof DesdeLaRaizRoute
  '/entrevista-previa': typeof EntrevistaPreviaRoute
  '/mentoria-maestras': typeof MentoriaMaestrasRoute
  '/mujer-re-nace': typeof MujerReNaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/admin/_protected': typeof AdminProtectedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_protected/entrevistas': typeof AdminProtectedEntrevistasRoute
  '/admin/_protected/metodologia': typeof AdminProtectedMetodologiaRoute
  '/admin/_protected/programas': typeof AdminProtectedProgramasRoute
  '/admin/_protected/sesiones': typeof AdminProtectedSesionesRoute
  '/admin/_protected/': typeof AdminProtectedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/dar-y-recibir'
    | '/desde-la-raiz'
    | '/entrevista-previa'
    | '/mentoria-maestras'
    | '/mujer-re-nace'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/admin'
    | '/admin/login'
    | '/admin/entrevistas'
    | '/admin/metodologia'
    | '/admin/programas'
    | '/admin/sesiones'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/dar-y-recibir'
    | '/desde-la-raiz'
    | '/entrevista-previa'
    | '/mentoria-maestras'
    | '/mujer-re-nace'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/admin/login'
    | '/admin/entrevistas'
    | '/admin/metodologia'
    | '/admin/programas'
    | '/admin/sesiones'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/dar-y-recibir'
    | '/desde-la-raiz'
    | '/entrevista-previa'
    | '/mentoria-maestras'
    | '/mujer-re-nace'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/admin/_protected'
    | '/admin/login'
    | '/admin/_protected/entrevistas'
    | '/admin/_protected/metodologia'
    | '/admin/_protected/programas'
    | '/admin/_protected/sesiones'
    | '/admin/_protected/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  DarYRecibirRoute: typeof DarYRecibirRoute
  DesdeLaRaizRoute: typeof DesdeLaRaizRoute
  EntrevistaPreviaRoute: typeof EntrevistaPreviaRoute
  MentoriaMaestrasRoute: typeof MentoriaMaestrasRoute
  MujerReNaceRoute: typeof MujerReNaceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreMiRoute: typeof SobreMiRoute
  AdminProtectedRoute: typeof AdminProtectedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mujer-re-nace': {
      id: '/mujer-re-nace'
      path: '/mujer-re-nace'
      fullPath: '/mujer-re-nace'
      preLoaderRoute: typeof MujerReNaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentoria-maestras': {
      id: '/mentoria-maestras'
      path: '/mentoria-maestras'
      fullPath: '/mentoria-maestras'
      preLoaderRoute: typeof MentoriaMaestrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevista-previa': {
      id: '/entrevista-previa'
      path: '/entrevista-previa'
      fullPath: '/entrevista-previa'
      preLoaderRoute: typeof EntrevistaPreviaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desde-la-raiz': {
      id: '/desde-la-raiz'
      path: '/desde-la-raiz'
      fullPath: '/desde-la-raiz'
      preLoaderRoute: typeof DesdeLaRaizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dar-y-recibir': {
      id: '/dar-y-recibir'
      path: '/dar-y-recibir'
      fullPath: '/dar-y-recibir'
      preLoaderRoute: typeof DarYRecibirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected/': {
      id: '/admin/_protected/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminProtectedIndexRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/sesiones': {
      id: '/admin/_protected/sesiones'
      path: '/sesiones'
      fullPath: '/admin/sesiones'
      preLoaderRoute: typeof AdminProtectedSesionesRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/programas': {
      id: '/admin/_protected/programas'
      path: '/programas'
      fullPath: '/admin/programas'
      preLoaderRoute: typeof AdminProtectedProgramasRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/metodologia': {
      id: '/admin/_protected/metodologia'
      path: '/metodologia'
      fullPath: '/admin/metodologia'
      preLoaderRoute: typeof AdminProtectedMetodologiaRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
    '/admin/_protected/entrevistas': {
      id: '/admin/_protected/entrevistas'
      path: '/entrevistas'
      fullPath: '/admin/entrevistas'
      preLoaderRoute: typeof AdminProtectedEntrevistasRouteImport
      parentRoute: typeof AdminProtectedRoute
    }
  }
}

interface AdminProtectedRouteChildren {
  AdminProtectedEntrevistasRoute: typeof AdminProtectedEntrevistasRoute
  AdminProtectedMetodologiaRoute: typeof AdminProtectedMetodologiaRoute
  AdminProtectedProgramasRoute: typeof AdminProtectedProgramasRoute
  AdminProtectedSesionesRoute: typeof AdminProtectedSesionesRoute
  AdminProtectedIndexRoute: typeof AdminProtectedIndexRoute
}

const AdminProtectedRouteChildren: AdminProtectedRouteChildren = {
  AdminProtectedEntrevistasRoute: AdminProtectedEntrevistasRoute,
  AdminProtectedMetodologiaRoute: AdminProtectedMetodologiaRoute,
  AdminProtectedProgramasRoute: AdminProtectedProgramasRoute,
  AdminProtectedSesionesRoute: AdminProtectedSesionesRoute,
  AdminProtectedIndexRoute: AdminProtectedIndexRoute,
}

const AdminProtectedRouteWithChildren = AdminProtectedRoute._addFileChildren(
  AdminProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  DarYRecibirRoute: DarYRecibirRoute,
  DesdeLaRaizRoute: DesdeLaRaizRoute,
  EntrevistaPreviaRoute: EntrevistaPreviaRoute,
  MentoriaMaestrasRoute: MentoriaMaestrasRoute,
  MujerReNaceRoute: MujerReNaceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreMiRoute: SobreMiRoute,
  AdminProtectedRoute: AdminProtectedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
